# -*- coding: utf-8 -*-
"""student_grade_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EWyKKbgxKA9l-h2hR_6mqCUJd3uxik_7
"""
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# --------------------------------
# Page Config
# --------------------------------
st.set_page_config(page_title="Student Grade Analysis", layout="wide")

st.title("🎓 Student Grade Analysis using Python")
st.subheader("Capstone Project – Data Analytics")

# --------------------------------
# Fixed Subjects
# --------------------------------
subjects = [
    "Mathematics I",
    "Computer Science",
    "Data Analytics",
    "English for Professionals"
]

# --------------------------------
# Number of Students
# --------------------------------
num_students = st.number_input(
    "Enter Number of Students",
    min_value=1,
    step=1
)

students = []

# --------------------------------
# Input Section
# --------------------------------
for i in range(num_students):
    st.markdown(f"## Student {i+1}")

    roll = st.text_input(f"Roll Number", key=f"roll{i}")
    name = st.text_input(f"Student Name", key=f"name{i}")

    marks = {}
    for sub in subjects:
        marks[sub] = st.number_input(
            f"Marks in {sub}",
            min_value=0,
            max_value=100,
            step=1,
            key=f"{sub}{i}"
        )

    if roll and name:
        total = sum(marks.values())
        percentage = total / len(subjects)
        cgpa = round(percentage / 10, 2)

        if percentage >= 80:
            grade = "A"
        elif percentage >= 60:
            grade = "B"
        elif percentage >= 40:
            grade = "C"
        else:
            grade = "D"

        students.append([
            roll, name,
            marks["Mathematics I"],
            marks["Computer Science"],
            marks["Data Analytics"],
            marks["English for Professionals"],
            total, round(percentage, 2), cgpa, grade
        ])

# --------------------------------
# Generate Result
# --------------------------------
if st.button("Generate Result") and students:

    columns = [
        "Roll No", "Name",
        "Maths", "CS", "DA", "English",
        "Total Marks", "Percentage", "CGPA", "Grade"
    ]

    df = pd.DataFrame(students, columns=columns)

    # --------------------------------
    # Result Table
    # --------------------------------
    st.subheader("📋 Result Table")
    st.dataframe(df)

    # --------------------------------
    # Top & Low Performer
    # --------------------------------
    top = df.loc[df["Total Marks"].idxmax()]
    low = df.loc[df["Total Marks"].idxmin()]

    col1, col2 = st.columns(2)
    col1.success(f"🏆 Top Performer: {top['Name']} ({top['Total Marks']} Marks)")
    col2.error(f"⬇ Low Performer: {low['Name']} ({low['Total Marks']} Marks)")

    # --------------------------------
    # Bar Graph
    # --------------------------------
    st.subheader("📊 Total Marks Bar Graph")
    fig, ax = plt.subplots()
    ax.bar(df["Name"], df["Total Marks"])
    ax.set_xlabel("Students")
    ax.set_ylabel("Total Marks")
    st.pyplot(fig)

    # --------------------------------
    # Grade Distribution Pie Chart
    # --------------------------------
    st.subheader("🥧 Grade Distribution")
    grade_counts = df["Grade"].value_counts()

    fig2, ax2 = plt.subplots()
    ax2.pie(
        grade_counts,
        labels=grade_counts.index,
        autopct="%1.1f%%",
        startangle=90
    )
    ax2.axis("equal")
    st.pyplot(fig2)
    # --------------------------------

    # --------------------------------
# Subject-wise Average Marks Bar Graph
# --------------------------------
st.subheader("📊 Subject-wise Average Marks")

subject_avg_df = pd.DataFrame({
    "Subject": [
        "Mathematics I",
        "Computer Science",
        "Data Analytics",
        "English for Professionals"
    ],
    "Average Marks": [
        df["Maths"].mean(),
        df["CS"].mean(),
        df["DA"].mean(),
        df["English"].mean()
    ]
})

fig3, ax3 = plt.subplots()
ax3.bar(subject_avg_df["Subject"], subject_avg_df["Average Marks"])
ax3.set_xlabel("Subjects")
ax3.set_ylabel("Average Marks")
ax3.set_ylim(0, 100)

st.pyplot(fig3)


    

    # --------------------------------
    # Subject Difficulty
    # --------------------------------
    st.subheader("📘 Subject Difficulty Analysis")

    subject_avg = {
        "Mathematics I": df["Maths"].mean(),
        "Computer Science": df["CS"].mean(),
        "Data Analytics": df["DA"].mean(),
        "English": df["English"].mean()
    }

    for sub, avg in subject_avg.items():
        if avg >= 70:
            st.success(f"{sub}: Easy")
        elif avg >= 50:
            st.warning(f"{sub}: Moderate")
        else:
            st.error(f"{sub}: Difficult")

else:
    st.info("Enter student details and click Generate Result")
