# -*- coding: utf-8 -*-
"""student_grade_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EWyKKbgxKA9l-h2hR_6mqCUJd3uxik_7
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.set_page_config(page_title="Student Performance Analysis", layout="wide")

st.title("📊 Student Performance Analysis System")

# -------------------------
# INPUT SECTION
# -------------------------
num_students = st.number_input("Enter number of students", min_value=1, step=1)

subjects = ["Math", "Physics", "Chemistry", "English", "Computer"]

students_data = []

for i in range(num_students):
    st.subheader(f"Student {i+1}")

    roll = st.text_input(f"Roll No {i+1}")
    name = st.text_input(f"Name {i+1}")

    marks = {}
    total_marks = 0

    for sub in subjects:
        m = st.number_input(f"{sub} Marks ({name})", min_value=0, max_value=100, key=f"{sub}{i}")
        marks[sub] = m
        total_marks += m

    percentage = total_marks / len(subjects)
    cgpa = round(percentage / 9.5, 2)

    students_data.append({
        "Roll No": roll,
        "Name": name,
        "Total Marks": total_marks,
        "Percentage": round(percentage, 2),
        "CGPA": cgpa,
        **marks
    })

# -------------------------
# PROCESS & OUTPUT
# -------------------------
if st.button("Generate Result"):

    df = pd.DataFrame(students_data)

    st.subheader("📋 Result Table")
    st.dataframe(df)

    # -------------------------
    # TOP & LOW PERFORMER
    # -------------------------
    top_student = df.loc[df["Percentage"].idxmax()]
    low_student = df.loc[df["Percentage"].idxmin()]

    col1, col2 = st.columns(2)

    with col1:
        st.success(f"🏆 Top Performer: {top_student['Name']} ({top_student['Percentage']}%)")

    with col2:
        st.error(f"⚠ Lower Performer: {low_student['Name']} ({low_student['Percentage']}%)")

    # -------------------------
    # BAR GRAPH (OVERALL)
    # -------------------------
    st.subheader("📊 Overall Percentage Bar Graph")

    fig, ax = plt.subplots()
    ax.bar(df["Name"], df["Percentage"])
    ax.set_ylabel("Percentage")
    ax.set_xlabel("Students")
    st.pyplot(fig)

    # -------------------------
    # SUBJECT DIFFICULTY
    # -------------------------
    subject_avg = df[subjects].mean()
    difficult_subject = subject_avg.idxmin()

    st.subheader("📉 Subject Analysis")
    st.write("### Subject Average Marks")
    st.write(subject_avg)

    st.warning(f"📌 Most Difficult Subject: **{difficult_subject}**")

    # -------------------------
    # SUBJECT AVERAGE GRAPH
    # -------------------------
    fig2, ax2 = plt.subplots()
    ax2.bar(subject_avg.index, subject_avg.values)
    ax2.set_ylabel("Average Marks")
    ax2.set_xlabel("Subjects")
    st.pyplot(fig2)
    st.subheader("📊 Grade Distribution (Pie Chart)")

# Grade count
grade_counts = df["Grade"].value_counts()

# Pie chart
fig, ax = plt.subplots()
ax.pie(
    grade_counts,
    labels=grade_counts.index,
    autopct='%1.1f%%',
    startangle=90
)
ax.axis('equal')  # circle banane ke liye

st.pyplot(fig)

