# -*- coding: utf-8 -*-
"""student_grade_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EWyKKbgxKA9l-h2hR_6mqCUJd3uxik_7
"""
from io import BytesIO
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# -------------------- PAGE SETUP --------------------
st.set_page_config(page_title="Student Grade Analysis", layout="wide")

st.title("🎓 Capstone Project – Comparative Students Performance Analysis: A Multi-Metric Review")
# ---------------- PROJECT INFORMATION ----------------

st.markdown("""
### 🎓 Capstone Project Details

**Group No:** 46  
**Group Members:**  
- MD Kabir  
- Naman Kabra  
- Vedant Kailash  

**College:** IIT PATNA  
**Course:** Computer Science & Data Analytics
""")


st.subheader("Data Analytics | Percentage | CGPA | Grade | Graphs")

# -------------------- SUBJECTS --------------------
subjects = [
    "Mathematics",
    "Physics",
    "Chemistry",
    "English",
    "Hindi"
]

# -------------------- INPUT: NUMBER OF STUDENTS --------------------
num_students = st.number_input(
    "Enter Number of Students",
    min_value=1,
    step=1
)

students_data = []

# -------------------- INPUT FORM --------------------
if num_students > 0:
    st.subheader("📝 Enter Student Details")

    for i in range(num_students):
        st.markdown(f"### Student {i+1}")

        roll = st.text_input(f"Roll Number", key=f"roll_{i}")
        name = st.text_input(f"Student Name", key=f"name_{i}")

        marks = {}
        total_marks = 0

        for sub in subjects:
            m = st.number_input(
                f"{sub} Marks",
                min_value=0,
                max_value=100,
                step=1,
                key=f"{sub}_{i}"
            )
            marks[sub] = m
            total_marks += m

        if roll and name:
            percentage = total_marks / len(subjects)
            cgpa = round(percentage / 9.5, 2)

            # Grade Logic
            if percentage >= 90:
                grade = "AA"
            elif percentage >= 80:
                grade = "AB"
            elif percentage >= 70:
                grade = "BB"
            elif percentage >= 60:
                grade = "BC"
            elif percentage >= 50:
                grade = "CC"
            elif percentage >= 40:
                grade = "DD"
            else:
                grade = "F"

            students_data.append({
                "Roll No": roll,
                "Name": name,
                "Percentage": round(percentage, 2),
                "CGPA": cgpa,
                "Grade": grade,
                **marks
            })

# -------------------- GENERATE RESULT --------------------
if st.button("📊 Generate Result"):

    if len(students_data) == 0:
        st.warning("Please enter student details first.")
    else:
        df = pd.DataFrame(students_data)

        st.subheader("📋 Result Table")
        st.dataframe(df)

# ---------------- DOWNLOAD AS CSV ----------------
        csv = df.to_csv(index=False).encode('utf-8')

        st.download_button(
            label="⬇ Download Results as CSV",
            data=csv,
            file_name="student_results.csv",
            mime="text/csv",
       )


        # ---------------- TOPPER & LOWEST ----------------
        topper = df.loc[df["Percentage"].idxmax()]
        lowest = df.loc[df["Percentage"].idxmin()]

        col1, col2 = st.columns(2)
        with col1:
            st.success(f"🏆 Topper: {topper['Name']} ({topper['Percentage']}%)")
        with col2:
            st.error(f"⬇ Lowest Performer: {lowest['Name']} ({lowest['Percentage']}%)")

        # ---------------- BAR GRAPH: STUDENT PERFORMANCE ----------------
        st.subheader("📊 Student Performance (Percentage)")

        fig1, ax1 = plt.subplots(figsize=(10, 6))

        # Find topper percentage
        top_percentage = df["Percentage"].max()

        # Assign colors
        bar_colors = []
        for _, row in df.iterrows():
            if row["Percentage"] == top_percentage:
               bar_colors.append("green")   # Topper
            elif row["Grade"] == "F":
                 bar_colors.append("red")     # Fail
            else:
                 bar_colors.append("steelblue")  # Others

        ax1.bar(df["Name"], df["Percentage"], color=bar_colors)

        ax1.set_ylabel("Percentage")
        ax1.set_xlabel("Students")
        ax1.set_title("Student vs Percentage Analysis")

        ax1.set_xticklabels(df["Name"], rotation=45, ha="right")

        plt.tight_layout()
        st.pyplot(fig1, use_container_width=True)

        # ---- Download Student Performance Graph ----
        buffer1 = BytesIO()
        fig1.savefig(buffer1, format="png")
        buffer1.seek(0)

        st.download_button(
            label="⬇ Download Student Performance Graph",
            data=buffer1,
            file_name="student_performance.png",
            mime="image/png"
       )

        

        # ---------------- PIE CHART: GRADE DISTRIBUTION ----------------
        st.subheader("🥧 Grade Distribution")
        grade_counts = df["Grade"].value_counts()

        fig2, ax2 = plt.subplots()
        ax2.pie(
            grade_counts,
            labels=grade_counts.index,
            autopct="%1.1f%%",
            startangle=90
        )
        ax2.axis("equal")
        st.pyplot(fig2)
        # ---- Download Grade Distribution Pie Chart ----
        buffer2 = BytesIO()
        fig2.savefig(buffer2, format="png")
        buffer2.seek(0)

        st.download_button(
            label="⬇ Download Grade Distribution Chart",
            data=buffer2,
            file_name="grade_distribution.png",
            mime="image/png"
        )

       

        # ---------------- SUBJECT AVERAGE BAR GRAPH ----------------
        st.subheader("📘 Subject-wise Average Marks")

        subject_avg = df[subjects].mean()

        colors = ["orange", "seagreen", "purple", "teal", "brown"]

        fig3, ax3 = plt.subplots()

        ax3.bar(subject_avg.index, subject_avg.values, color=colors)

        ax3.set_ylabel("Average Marks")
        ax3.set_xlabel("Subjects")
        ax3.set_title("Average Marks per Subject")

        plt.tight_layout()
        st.pyplot(fig3)

        # ---- Download Subject Average Graph ----
        buffer3 = BytesIO()
        fig3.savefig(buffer3, format="png")
        buffer3.seek(0)

        st.download_button(
            label="⬇ Download Subject Average Graph",
            data=buffer3,
            file_name="subject_average.png",
            mime="image/png"
        )



        # ---------------- SUBJECT DIFFICULTY ----------------
        st.subheader("📉 Subject Difficulty Analysis")
        hardest = subject_avg.idxmin()
        easiest = subject_avg.idxmax()

        st.info(f"Hardest Subject: {hardest}")
        st.success(f"Easiest Subject: {easiest}")
